#!/bin/bash

#getting the username
USERNAME=$(whoami)

#Current date and time
DATETIME=$(date)

#getting the hostname
HOSTNAME=$(hostname)

#uptime of the system
UPTIME=$(uptime -p)

#Hardware information
CPUINFO=$(sudo lscpu | grep 'Model name' | awk -F: '{print $2}' | xargs)
CPUSPEED=$(sudo lshw -C cpu | grep -i speed | awk '{print $2}')
RAMSIZE=$(sudo free -h | grep 'Mem' | awk '{print $2}')
DISKS=$(sudo lsblk -d -o model,size | tail -n +2)

#Network Information
FQDN=$(hostname -f)
IP_ADDRESS=$(hostname -I | awk '{print $1}')
Gateway=$(ip r | grep default | awk '{print $3}')


#System status
Users_logged_in=$(who | awk '{print $1}')
Process_Count=$(ps -A | wc -l)

cat << Report
System report generated by $USERNAME, $DATETIME

System Information
----------------
Hostname: $HOSTNAME
OS: $DISTROWITHVERSION
Uptime: $UPTIME

Hardware Information
-------------------
cpu: $CPUINFO
speed: $CPUSPEED
Ram: $RAMSIZE
Disk(s): $DISKS

Network Information
-----------------
fqdn: $FQDN
IP_ADDRESS: $IP_ADDRESS
Default_Gateway: $Gateway

System Status
------------
users_logged_in: $Users_logged_in
process_count: $Process_Count
Report
